name: build and push the build files to anothe repo

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          repository: itsdevdeepak/itsdevdeepak.github.io
          path: itsdevdeepak
          ref: main
          token: ${{ secrets.REPO_TOKEN }}
      
      - name: list clone
        run: ls -lash
        
      - name: install dependency 
        run: npm i
        
      - name: Build
        run: npm run build
        
      - name: list
        run: ls itsdevdeepak/ 
        
      - name: print dir
        run: pwd
        
      - name: Copy build files
        run: cp -r dist/* itsdevdeepak/

      - name: Commit and push changes
        run: |
          cd target-repo
          git config user.email "deepak.k13@outlook.com"
          git config user.name "Deepak"
          git add .
          git commit -m "Add build files"
          git push origin main
